### ISSUE TITLE
Redesign of build process

### ISSUE THREAD

**Issue by fredrikaverpil** [fredrikaverpil/pyside2-wheels#64]
I'm considering changing the build process on all platforms:

- Use pre-built docker images on Linux, stored on dockerhub to speed up the pre-build phase
- Utilize [JOM](https://github.com/fredrikaverpil/pyside2-wheels/issues/62) for parallel PySide2 build commands, speeding up the build process
- Conform to using/requiring conda on all platforms for building and then also installing/using PySide2
- Possibly publish the wheels on conda-forge allowing for very simple quickstarts, given the user already is using conda.

What would you guys say about using conda instead of the current setups?

**Comment by leycec** [comment]
Everything sounds *fabulous,* except that whole **"Conform to using/requiring `conda` on all platforms for building and then also installing/using PySide2"** part.

The [Ana|Mini]conda distribution is fairly heavyweight and specialized for use in scientific computing. While leveraging `conda-forge` to publish [Ana|Mini]conda packages *would* dramatically simplify PySide2 installation for [Ana|Mini]conda users (and hence would be a very good thing), doing so should ideally be done *in addition to* rather than *instead of* publishing PyPI-distributed wheels.

The two communities serve different needs and are largely orthogonal. While our [downstream multiphysics simulator](https://gitlab.com/betse/betse) personally recommends use of [Ana|Mini]conda to simplify installation, we have a hardcore contingent of CLI-oriented users who prefer a manual installation leveraging some combination of `pip3` and their system-wide package manager (e.g., `apt`). They are painfully loud and refuse to use [Ana|Mini]conda. In short, they are people like me.

It'd be great if we could continue to service both communities.

**Comment by fredrikaverpil** [comment]
Yes, I agree. I think adding conda-built wheels (so to speak), could be a nice addition rather than a replacement.

**Comment by fredrikaverpil** [comment]
@leycec PySide2 now available on Anaconda Cloud: https://github.com/conda-forge/pyside2-feedstock ❤️
