### ISSUE TITLE
The license of PySide2 has not yet been decided upon

### ISSUE THREAD

**Issue by fredrikaverpil** [fredrikaverpil/pyside2-wheels#96]
I just found out about [this](https://gitter.im/PySide/pyside2?at=59a52b4bee5c9a4c5f0ea815), as this is not stated in the PySide2 wiki. I believe this could be useful information for anyone investing time and money into PySide2.

Here's a googlegroups discussion on the licensing: https://groups.google.com/forum/#!topic/pyside-dev/pqwzngAGLWE

**Comment by albertosottile** [comment]
As you stated on gitter, this is quite THE issue, especially for people that want to build redistributable apps and do not want/cannot switch to GPL (cough cough, PyQt5). Also, Anaconda people seems to ignore this, since they stated LGPL3 as PySide2 license both [here](https://github.com/conda-forge/pyside2-feedstock) and [here](https://anaconda.org/conda-forge/pyside2).

**Comment by hmaarrfk** [comment]
Is this still the case?

The PySide2 wiki states that they "Need to decide on Licensing for Product placement decisions"
but the COPYING file in their source tree keeps the LGPLv3 license.

https://github.com/pyside/pyside2-setup/tree/5.6/sources/pyside2
